### ISSUE TITLE
Breaks the whole server

### ISSUE THREAD

**Issue by VertoxenYT** [Trxgically/SpawnsCore#4]
**When i put in the plugin, it crashes the whole server and stops it from starting.**

**Comment by Trxgically** [comment]
This is a long-forgotten plugin but if you would like me to update & fix I'd be able to do that.

**Comment by VertoxenYT** [comment]
please do, add it into poggit if you can, this will add alot of publicity to the plugin because there is barely any plugins like this with /hub that work.

**Comment by Trxgically** [comment]
I fixed it, I'm currently testing a few things right now.

**Comment by VertoxenYT** [comment]
ok, thank you so much!

**Comment by Trxgically** [comment]
Also I did submit it to Poggit but they didn't accept it as it "not useful" but poggit says it has 3 errors when I pushed the updated main.php for some reason when its completely fine..? [https://poggit.pmmp.io/ci/Trxgically/SpawnsCore/SpawnsCore](url)

**Comment by Trxgically** [comment]
When you run it & test it out let me know so I can close this issue.

**Comment by VertoxenYT** [comment]
mabye its bcs they have the MSpawns plugin, but i need to report to them that the plugin is broken, and this in-fact is very useful

**Comment by Trxgically** [comment]
Yeah, read this. [https://github.com/Trxgically/SpawnsCore/commit/9165fc498a886093c57e8646abc20b7489480410](url)

**Comment by Trxgically** [comment]
https://github.com/Trxgically/SpawnsCore/commit/9165fc498a886093c57e8646abc20b7489480410

**Comment by VertoxenYT** [comment]
mabye remove /setlobby and make it only /sethub and /setspawn, but keep /lobby, make it an alias of /spawn

**Comment by VertoxenYT** [comment]
if i dont respond, that means i am sleeping

**Comment by Trxgically** [comment]
kk well did you test?

**Comment by VertoxenYT** [comment]
i have run into some issues starting the server, don't worry, it isn't the plugin's fault, its the host's fault

**Comment by VertoxenYT** [comment]
they are building a new node that will take 5 hours to finish due to the panel layout. I will be asleep by then, but i will happily test your plugin tommorow! Or you can test it.

**Comment by Trxgically** [comment]
On my end the plugin works, therefore I will close this and confirm this is no longer an issue.
